Metadata:
  AWS::ServerlessRepo::Application:
    Name: EdgeDelta-Lambda-Extension-Layer-AMD64
    Description: Edge Delta lambda extension to monitor AWS lambda functions.
    Author: Edge Delta
    ReadmeUrl: README.md
    LicenseUrl: LICENSE
    SpdxLicenseId: Apache-2.0
    HomePageUrl: https://github.com/edgedelta/edgedelta-lambda-extension
    SemanticVersion: 0.0.1
    SourceCodeUrl: https://github.com/edgedelta/edgedelta-lambda-extension

AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Outputs:
  LayerVersion:
    Description: Layer ARN Reference
    Value:
      Ref: LambdaLayer
Resources:
  LambdaLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: edgedelta-lambda-extension
      Description: Edge Delta lambda extension to monitor AWS lambda functions.
      ContentUri: s3://ed-dev-serverless-repository/extension_amd64_0.0.1.zip
      CompatibleRuntimes:
        - go1.x
